import { createFileRoute, Link } from "@tanstack/react-router";
import { FileSearch, Gavel, ShieldCheck, Eye, MessageCircle } from "lucide-react";
import heroImg from "@/assets/hero-services.jpg";
import { buildHead, SITE_URL } from "@/lib/seo";
import { Breadcrumbs } from "@/components/site/Breadcrumbs";
import { CONTACT } from "@/lib/site-data";
import { trackEvent } from "@/lib/analytics";

const SECTIONS = [
  {
    icon: FileSearch,
    title: "What a VIN Actually Tells You",
    body: "The Vehicle Identification Number confirms the manufacturer, model, year, and production details of a specific vehicle. On its own, it doesn't tell you about accidents, title status, or condition — that information comes from separate history reports pulled using the VIN.",
  },
  {
    icon: FileSearch,
    title: "Carfax and AutoCheck",
    body: "These reports compile records reported by insurers, auctions, DMVs, and service centers in the US and Canada — title changes, reported accidents, odometer readings, and service history where available. Coverage depends entirely on what's been reported; unreported damage or unofficial repairs won't appear.",
  },
  {
    icon: Gavel,
    title: "Auction History and Condition Reports",
    body: "US auction platforms like Copart and IAAI publish their own condition grading and damage descriptions for each lot. These are useful, but they're generated by the auction itself — not an independent third party — and are not a substitute for physical inspection.",
  },
  {
    icon: FileSearch,
    title: "Korean Vehicle History",
    body: "South Korea's mandatory periodic technical inspections generate a more standardized service and condition history than in many other markets, which is part of why Korean vehicles often have a strong maintenance reputation. Platforms like Encar publish grading and condition summaries based on this.",
  },
  {
    icon: ShieldCheck,
    title: "Why Inspections Still Matter",
    body: "History reports and auction grading tell you what's been recorded. They don't replace a hands-on check for mechanical condition, hidden damage, or issues that never made it into any report. This is why we treat inspection as a separate, complementary step — not an alternative to a good history report.",
  },
  {
    icon: Eye,
    title: "What Reports Can't Show You",
    body: "No report can confirm current mechanical condition, a fresh problem that occurred after the last data update, or damage that was repaired without being reported. This is a real limitation of every history-report system, not just the ones we've mentioned here.",
  },
];

const FAQS = [
  { q: "Is a clean Carfax report a guarantee the vehicle has no issues?", a: "No. A clean report means no reportable incidents were found in the databases it checks — it doesn't mean the vehicle has no mechanical issues or that every incident was ever reported in the first place." },
  { q: "Do Korean vehicles need the same history checks as US vehicles?", a: "Korean vehicles use a different reporting system, generally built around South Korea's mandatory periodic inspections rather than Carfax/AutoCheck. Platforms like Encar summarize this history and grading directly." },
  { q: "Can Alpha Worldwide pull a history report for me?", a: "We review the available history and condition information for a specific vehicle before recommending a purchase decision, and can coordinate a physical inspection where that's operationally possible." },
  { q: "Is inspection always available before I buy?", a: "No — inspection availability depends on the seller, the auction, and access to the vehicle. We confirm what's realistic for your specific listing before you commit to a purchase." },
];

export const Route = createFileRoute("/vehicle-history-check")({
  head: () => {
    const base = buildHead({
      title: "Vehicle History Checks Explained | VIN, Carfax, AutoCheck",
      description: "What VIN, Carfax, and AutoCheck reports can and can't show you, how Korean vehicle history differs, and why physical inspection is still often necessary.",
      path: "/vehicle-history-check",
      image: heroImg,
    });
    return {
      ...base,
      scripts: [
        {
          type: "application/ld+json",
          children: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Article",
            headline: "Vehicle History Checks Explained",
            description: "What VIN, Carfax, AutoCheck, and Korean vehicle history reports can and cannot show, and when physical inspection is still required.",
            author: { "@type": "Organization", name: "Alpha Worldwide" },
            publisher: { "@type": "Organization", name: "Alpha Worldwide", url: SITE_URL },
            url: `${SITE_URL}/vehicle-history-check`,
          }),
        },
        {
          type: "application/ld+json",
          children: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: FAQS.map((f) => ({
              "@type": "Question",
              name: f.q,
              acceptedAnswer: { "@type": "Answer", text: f.a },
            })),
          }),
        },
      ],
    };
  },
  component: VehicleHistoryCheck,
});

function VehicleHistoryCheck() {
  const whatsappUrl = `https://wa.me/${CONTACT.whatsapp}?text=${encodeURIComponent(
    "Hello Alpha Worldwide, I'd like to understand the history and condition of a vehicle I'm considering.",
  )}`;

  return (
    <>
      <Breadcrumbs items={[{ label: "Vehicle History Check" }]} />
      <section className="relative isolate overflow-hidden text-white">
        <img src={heroImg} alt="Reviewing vehicle history and inspection documentation" width={1920} height={900} className="absolute inset-0 -z-10 h-full w-full object-cover" />
        <div className="absolute inset-0 -z-10 bg-gradient-to-br from-navy/95 via-navy/85 to-graphite/90" />
        <div className="container-page flex min-h-[45vh] flex-col justify-end py-28">
          <div className="max-w-3xl animate-fade-up">
            <div className="eyebrow text-teal-glow">Buyer education</div>
            <h1 className="font-display mt-4 text-4xl font-bold leading-[1.05] md:text-6xl">
              What a Vehicle History Report Can (and Can't) Tell You
            </h1>
            <p className="mt-5 max-w-2xl text-lg text-white/75">
              VIN checks, Carfax, AutoCheck, and Korean vehicle history — how they work, their real limitations, and why physical inspection is still often necessary.
            </p>
          </div>
        </div>
      </section>

      <section className="bg-background">
        <div className="container-page py-16 md:py-20">
          <div className="mx-auto max-w-3xl space-y-10">
            {SECTIONS.map((s) => (
              <div key={s.title} className="flex gap-5">
                <div className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-teal/10 text-teal">
                  <s.icon className="h-5 w-5" />
                </div>
                <div>
                  <h2 className="font-display text-xl font-bold text-navy">{s.title}</h2>
                  <p className="mt-2 text-sm leading-relaxed text-slate-body">{s.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section-mist">
        <div className="container-page py-16 md:py-20">
          <div className="mx-auto max-w-2xl text-center">
            <div className="eyebrow">Related reading</div>
            <h2 className="font-display mt-3 text-3xl font-bold text-navy md:text-4xl">Go Deeper</h2>
          </div>
          <div className="mx-auto mt-8 flex max-w-2xl flex-wrap items-center justify-center gap-3">
            <Link to="/inspection-service" className="rounded-full border border-border bg-card px-5 py-2.5 text-sm font-semibold text-navy transition-colors hover:border-teal hover:text-teal">
              Our inspection service
            </Link>
            <Link to="/import-usa" className="rounded-full border border-border bg-card px-5 py-2.5 text-sm font-semibold text-navy transition-colors hover:border-teal hover:text-teal">
              Buying from US auctions
            </Link>
            <Link to="/import-korea" className="rounded-full border border-border bg-card px-5 py-2.5 text-sm font-semibold text-navy transition-colors hover:border-teal hover:text-teal">
              Buying from South Korea
            </Link>
          </div>
        </div>
      </section>

      <section className="bg-background">
        <div className="container-page py-16 md:py-20">
          <div className="mx-auto max-w-2xl text-center">
            <div className="eyebrow">Questions</div>
            <h2 className="font-display mt-3 text-3xl font-bold text-navy md:text-4xl">Frequently Asked</h2>
          </div>
          <div className="mx-auto mt-10 max-w-2xl divide-y divide-border rounded-2xl border border-border bg-card">
            {FAQS.map((f) => (
              <details key={f.q} className="group p-5">
                <summary className="flex cursor-pointer items-center justify-between gap-4 text-sm font-semibold text-navy">
                  {f.q}
                  <span className="text-teal transition-transform group-open:rotate-45">+</span>
                </summary>
                <p className="mt-3 text-sm leading-relaxed text-slate-body">{f.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      <section className="section-dark">
        <div className="container-page py-16 text-center md:py-20">
          <a
            href={whatsappUrl}
            target="_blank"
            rel="noreferrer noopener"
            onClick={() => trackEvent("whatsapp_clicked", { source: "vehicle-history-final-cta" })}
            className="btn-primary"
          >
            <MessageCircle className="h-4 w-4" /> Ask About a Specific Vehicle
          </a>
        </div>
      </section>
    </>
  );
}
