/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingCalculatorRouteImport } from './routes/shipping-calculator'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RoroShippingRouteImport } from './routes/roro-shipping'
import { Route as InspectionServiceRouteImport } from './routes/inspection-service'
import { Route as ImportUsaRouteImport } from './routes/import-usa'
import { Route as ImportUaeRouteImport } from './routes/import-uae'
import { Route as ImportKoreaRouteImport } from './routes/import-korea'
import { Route as ImportEuropeRouteImport } from './routes/import-europe'
import { Route as ImportCanadaRouteImport } from './routes/import-canada'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeliveredVehiclesRouteImport } from './routes/delivered-vehicles'
import { Route as ContainerShippingRouteImport } from './routes/container-shipping'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuctionAccessRouteImport } from './routes/auction-access'
import { Route as AirfreightRouteImport } from './routes/airfreight'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlIndexRouteImport } from './routes/al/index'
import { Route as EnNetherlandsRouteImport } from './routes/en/netherlands'
import { Route as EnAlbaniaRouteImport } from './routes/en/albania'
import { Route as AlMakinaNgaAmerikaRouteImport } from './routes/al/makina-nga-amerika'
import { Route as AlKontaktRouteImport } from './routes/al/kontakt'
import { Route as EnShippingSouthKoreaToRotterdamRouteImport } from './routes/en/shipping/south-korea-to-rotterdam'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingCalculatorRoute = ShippingCalculatorRouteImport.update({
  id: '/shipping-calculator',
  path: '/shipping-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RoroShippingRoute = RoroShippingRouteImport.update({
  id: '/roro-shipping',
  path: '/roro-shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionServiceRoute = InspectionServiceRouteImport.update({
  id: '/inspection-service',
  path: '/inspection-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportUsaRoute = ImportUsaRouteImport.update({
  id: '/import-usa',
  path: '/import-usa',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportUaeRoute = ImportUaeRouteImport.update({
  id: '/import-uae',
  path: '/import-uae',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportKoreaRoute = ImportKoreaRouteImport.update({
  id: '/import-korea',
  path: '/import-korea',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportEuropeRoute = ImportEuropeRouteImport.update({
  id: '/import-europe',
  path: '/import-europe',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportCanadaRoute = ImportCanadaRouteImport.update({
  id: '/import-canada',
  path: '/import-canada',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveredVehiclesRoute = DeliveredVehiclesRouteImport.update({
  id: '/delivered-vehicles',
  path: '/delivered-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainerShippingRoute = ContainerShippingRouteImport.update({
  id: '/container-shipping',
  path: '/container-shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAccessRoute = AuctionAccessRouteImport.update({
  id: '/auction-access',
  path: '/auction-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AirfreightRoute = AirfreightRouteImport.update({
  id: '/airfreight',
  path: '/airfreight',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlIndexRoute = AlIndexRouteImport.update({
  id: '/al/',
  path: '/al/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNetherlandsRoute = EnNetherlandsRouteImport.update({
  id: '/en/netherlands',
  path: '/en/netherlands',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAlbaniaRoute = EnAlbaniaRouteImport.update({
  id: '/en/albania',
  path: '/en/albania',
  getParentRoute: () => rootRouteImport,
} as any)
const AlMakinaNgaAmerikaRoute = AlMakinaNgaAmerikaRouteImport.update({
  id: '/al/makina-nga-amerika',
  path: '/al/makina-nga-amerika',
  getParentRoute: () => rootRouteImport,
} as any)
const AlKontaktRoute = AlKontaktRouteImport.update({
  id: '/al/kontakt',
  path: '/al/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const EnShippingSouthKoreaToRotterdamRoute =
  EnShippingSouthKoreaToRotterdamRouteImport.update({
    id: '/en/shipping/south-korea-to-rotterdam',
    path: '/en/shipping/south-korea-to-rotterdam',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airfreight': typeof AirfreightRoute
  '/auction-access': typeof AuctionAccessRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/container-shipping': typeof ContainerShippingRoute
  '/delivered-vehicles': typeof DeliveredVehiclesRoute
  '/faq': typeof FaqRoute
  '/import-canada': typeof ImportCanadaRoute
  '/import-europe': typeof ImportEuropeRoute
  '/import-korea': typeof ImportKoreaRoute
  '/import-uae': typeof ImportUaeRoute
  '/import-usa': typeof ImportUsaRoute
  '/inspection-service': typeof InspectionServiceRoute
  '/roro-shipping': typeof RoroShippingRoute
  '/services': typeof ServicesRoute
  '/shipping-calculator': typeof ShippingCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/al/kontakt': typeof AlKontaktRoute
  '/al/makina-nga-amerika': typeof AlMakinaNgaAmerikaRoute
  '/en/albania': typeof EnAlbaniaRoute
  '/en/netherlands': typeof EnNetherlandsRoute
  '/al/': typeof AlIndexRoute
  '/en/shipping/south-korea-to-rotterdam': typeof EnShippingSouthKoreaToRotterdamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airfreight': typeof AirfreightRoute
  '/auction-access': typeof AuctionAccessRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/container-shipping': typeof ContainerShippingRoute
  '/delivered-vehicles': typeof DeliveredVehiclesRoute
  '/faq': typeof FaqRoute
  '/import-canada': typeof ImportCanadaRoute
  '/import-europe': typeof ImportEuropeRoute
  '/import-korea': typeof ImportKoreaRoute
  '/import-uae': typeof ImportUaeRoute
  '/import-usa': typeof ImportUsaRoute
  '/inspection-service': typeof InspectionServiceRoute
  '/roro-shipping': typeof RoroShippingRoute
  '/services': typeof ServicesRoute
  '/shipping-calculator': typeof ShippingCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/al/kontakt': typeof AlKontaktRoute
  '/al/makina-nga-amerika': typeof AlMakinaNgaAmerikaRoute
  '/en/albania': typeof EnAlbaniaRoute
  '/en/netherlands': typeof EnNetherlandsRoute
  '/al': typeof AlIndexRoute
  '/en/shipping/south-korea-to-rotterdam': typeof EnShippingSouthKoreaToRotterdamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airfreight': typeof AirfreightRoute
  '/auction-access': typeof AuctionAccessRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/container-shipping': typeof ContainerShippingRoute
  '/delivered-vehicles': typeof DeliveredVehiclesRoute
  '/faq': typeof FaqRoute
  '/import-canada': typeof ImportCanadaRoute
  '/import-europe': typeof ImportEuropeRoute
  '/import-korea': typeof ImportKoreaRoute
  '/import-uae': typeof ImportUaeRoute
  '/import-usa': typeof ImportUsaRoute
  '/inspection-service': typeof InspectionServiceRoute
  '/roro-shipping': typeof RoroShippingRoute
  '/services': typeof ServicesRoute
  '/shipping-calculator': typeof ShippingCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/al/kontakt': typeof AlKontaktRoute
  '/al/makina-nga-amerika': typeof AlMakinaNgaAmerikaRoute
  '/en/albania': typeof EnAlbaniaRoute
  '/en/netherlands': typeof EnNetherlandsRoute
  '/al/': typeof AlIndexRoute
  '/en/shipping/south-korea-to-rotterdam': typeof EnShippingSouthKoreaToRotterdamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/airfreight'
    | '/auction-access'
    | '/calculator'
    | '/contact'
    | '/container-shipping'
    | '/delivered-vehicles'
    | '/faq'
    | '/import-canada'
    | '/import-europe'
    | '/import-korea'
    | '/import-uae'
    | '/import-usa'
    | '/inspection-service'
    | '/roro-shipping'
    | '/services'
    | '/shipping-calculator'
    | '/sitemap.xml'
    | '/al/kontakt'
    | '/al/makina-nga-amerika'
    | '/en/albania'
    | '/en/netherlands'
    | '/al/'
    | '/en/shipping/south-korea-to-rotterdam'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/airfreight'
    | '/auction-access'
    | '/calculator'
    | '/contact'
    | '/container-shipping'
    | '/delivered-vehicles'
    | '/faq'
    | '/import-canada'
    | '/import-europe'
    | '/import-korea'
    | '/import-uae'
    | '/import-usa'
    | '/inspection-service'
    | '/roro-shipping'
    | '/services'
    | '/shipping-calculator'
    | '/sitemap.xml'
    | '/al/kontakt'
    | '/al/makina-nga-amerika'
    | '/en/albania'
    | '/en/netherlands'
    | '/al'
    | '/en/shipping/south-korea-to-rotterdam'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/airfreight'
    | '/auction-access'
    | '/calculator'
    | '/contact'
    | '/container-shipping'
    | '/delivered-vehicles'
    | '/faq'
    | '/import-canada'
    | '/import-europe'
    | '/import-korea'
    | '/import-uae'
    | '/import-usa'
    | '/inspection-service'
    | '/roro-shipping'
    | '/services'
    | '/shipping-calculator'
    | '/sitemap.xml'
    | '/al/kontakt'
    | '/al/makina-nga-amerika'
    | '/en/albania'
    | '/en/netherlands'
    | '/al/'
    | '/en/shipping/south-korea-to-rotterdam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AirfreightRoute: typeof AirfreightRoute
  AuctionAccessRoute: typeof AuctionAccessRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  ContainerShippingRoute: typeof ContainerShippingRoute
  DeliveredVehiclesRoute: typeof DeliveredVehiclesRoute
  FaqRoute: typeof FaqRoute
  ImportCanadaRoute: typeof ImportCanadaRoute
  ImportEuropeRoute: typeof ImportEuropeRoute
  ImportKoreaRoute: typeof ImportKoreaRoute
  ImportUaeRoute: typeof ImportUaeRoute
  ImportUsaRoute: typeof ImportUsaRoute
  InspectionServiceRoute: typeof InspectionServiceRoute
  RoroShippingRoute: typeof RoroShippingRoute
  ServicesRoute: typeof ServicesRoute
  ShippingCalculatorRoute: typeof ShippingCalculatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AlKontaktRoute: typeof AlKontaktRoute
  AlMakinaNgaAmerikaRoute: typeof AlMakinaNgaAmerikaRoute
  EnAlbaniaRoute: typeof EnAlbaniaRoute
  EnNetherlandsRoute: typeof EnNetherlandsRoute
  AlIndexRoute: typeof AlIndexRoute
  EnShippingSouthKoreaToRotterdamRoute: typeof EnShippingSouthKoreaToRotterdamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-calculator': {
      id: '/shipping-calculator'
      path: '/shipping-calculator'
      fullPath: '/shipping-calculator'
      preLoaderRoute: typeof ShippingCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roro-shipping': {
      id: '/roro-shipping'
      path: '/roro-shipping'
      fullPath: '/roro-shipping'
      preLoaderRoute: typeof RoroShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection-service': {
      id: '/inspection-service'
      path: '/inspection-service'
      fullPath: '/inspection-service'
      preLoaderRoute: typeof InspectionServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-usa': {
      id: '/import-usa'
      path: '/import-usa'
      fullPath: '/import-usa'
      preLoaderRoute: typeof ImportUsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-uae': {
      id: '/import-uae'
      path: '/import-uae'
      fullPath: '/import-uae'
      preLoaderRoute: typeof ImportUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-korea': {
      id: '/import-korea'
      path: '/import-korea'
      fullPath: '/import-korea'
      preLoaderRoute: typeof ImportKoreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-europe': {
      id: '/import-europe'
      path: '/import-europe'
      fullPath: '/import-europe'
      preLoaderRoute: typeof ImportEuropeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-canada': {
      id: '/import-canada'
      path: '/import-canada'
      fullPath: '/import-canada'
      preLoaderRoute: typeof ImportCanadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivered-vehicles': {
      id: '/delivered-vehicles'
      path: '/delivered-vehicles'
      fullPath: '/delivered-vehicles'
      preLoaderRoute: typeof DeliveredVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/container-shipping': {
      id: '/container-shipping'
      path: '/container-shipping'
      fullPath: '/container-shipping'
      preLoaderRoute: typeof ContainerShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction-access': {
      id: '/auction-access'
      path: '/auction-access'
      fullPath: '/auction-access'
      preLoaderRoute: typeof AuctionAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airfreight': {
      id: '/airfreight'
      path: '/airfreight'
      fullPath: '/airfreight'
      preLoaderRoute: typeof AirfreightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/al/': {
      id: '/al/'
      path: '/al'
      fullPath: '/al/'
      preLoaderRoute: typeof AlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/netherlands': {
      id: '/en/netherlands'
      path: '/en/netherlands'
      fullPath: '/en/netherlands'
      preLoaderRoute: typeof EnNetherlandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/albania': {
      id: '/en/albania'
      path: '/en/albania'
      fullPath: '/en/albania'
      preLoaderRoute: typeof EnAlbaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/al/makina-nga-amerika': {
      id: '/al/makina-nga-amerika'
      path: '/al/makina-nga-amerika'
      fullPath: '/al/makina-nga-amerika'
      preLoaderRoute: typeof AlMakinaNgaAmerikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/al/kontakt': {
      id: '/al/kontakt'
      path: '/al/kontakt'
      fullPath: '/al/kontakt'
      preLoaderRoute: typeof AlKontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/shipping/south-korea-to-rotterdam': {
      id: '/en/shipping/south-korea-to-rotterdam'
      path: '/en/shipping/south-korea-to-rotterdam'
      fullPath: '/en/shipping/south-korea-to-rotterdam'
      preLoaderRoute: typeof EnShippingSouthKoreaToRotterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AirfreightRoute: AirfreightRoute,
  AuctionAccessRoute: AuctionAccessRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  ContainerShippingRoute: ContainerShippingRoute,
  DeliveredVehiclesRoute: DeliveredVehiclesRoute,
  FaqRoute: FaqRoute,
  ImportCanadaRoute: ImportCanadaRoute,
  ImportEuropeRoute: ImportEuropeRoute,
  ImportKoreaRoute: ImportKoreaRoute,
  ImportUaeRoute: ImportUaeRoute,
  ImportUsaRoute: ImportUsaRoute,
  InspectionServiceRoute: InspectionServiceRoute,
  RoroShippingRoute: RoroShippingRoute,
  ServicesRoute: ServicesRoute,
  ShippingCalculatorRoute: ShippingCalculatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AlKontaktRoute: AlKontaktRoute,
  AlMakinaNgaAmerikaRoute: AlMakinaNgaAmerikaRoute,
  EnAlbaniaRoute: EnAlbaniaRoute,
  EnNetherlandsRoute: EnNetherlandsRoute,
  AlIndexRoute: AlIndexRoute,
  EnShippingSouthKoreaToRotterdamRoute: EnShippingSouthKoreaToRotterdamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
